<?php
require_once __DIR__ . '/../../config.php';

class Model {
    protected $db;

    public function __construct() {
        $this->db = new PDO(
            'mysql:host=' . MYSQL_HOST . ";charset=utf8",
            MYSQL_USER,
            MYSQL_PASS
        );

        $this->db->query("CREATE DATABASE IF NOT EXISTS `" . MYSQL_DB . "` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

        $this->db= new PDO(
            "mysql:host=" . MYSQL_HOST . ";dbname=" . MYSQL_DB . ";charset=utf8",
            MYSQL_USER,
            MYSQL_PASS
        );

        $this-> _deploy();
    }

    private function _deploy(){
        $query=$this->db->query('SHOW TABLES');
        $tables=$query->fetchAll();


        if(count($tables)==0){
            $sql=<<<'SQL'
            CREATE TABLE IF NOT EXISTS `usuarios` (
            `id_usuario` int(11) NOT NULL AUTO_INCREMENT,
            `email` varchar(50) NOT NULL,
            `password` varchar(255) NOT NULL,
            PRIMARY KEY (`id_usuario`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

            INSERT INTO `usuarios` (`id_usuario`, `email`, `password`) VALUES
            (1, 'webadmin@admin.com', '\$2y\$10\$BqvTeEdws5Osoh1.j4wiLOklzeM1BwAgMYhMjMiv4wyjiJJvtTMka');

            CREATE TABLE IF NOT EXISTS `artista` (
            `id_artista` int(11) NOT NULL AUTO_INCREMENT,
            `nombre_completo` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
            `fecha_nacimiento` date NOT NULL,
            `fecha_fallecimiento` date DEFAULT NULL,
            `corriente_artistica` varchar(150) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
            `nacionalidad` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
            `biografia` text CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
            `imagen` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
            PRIMARY KEY (`id_artista`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

            INSERT INTO `artista` (`id_artista`, `nombre_completo`, `fecha_nacimiento`, `fecha_fallecimiento`, `corriente_artistica`, `nacionalidad`, `biografia`, `imagen`) VALUES
            (1, 'Claude Monet', '1840-11-14', '1926-12-05', 'Impresionismo', 'Frances', 'Pintor francés, fundador del impresionismo. Maestro de la luz y el color, célebre por su serie Nenúfares y las vistas de la Catedral de Rouen.', 'https://uploads0.wikiart.org/00115/images/claude-monet/440px-claude-monet-1899-nadar-crop.jpg!Portrait.jpg'),
            (2, 'Guillermo Bert', '1959-02-28', NULL, 'Arte Conceptual, Arte de Instalación', 'Chileno', 'Chileno nacido en 1959, vive en Los Ángeles. Artista multimedia que fusiona tecnología, textiles indígenas y escultura para visibilizar la identidad y migración latina.', 'https://images.squarespace-cdn.com/content/v1/65c010c4a792fd0dd6dc7290/6bd872ee-5aab-4b84-9026-b1d5c4126dab/Guillermo-Bert-2019.jpg'),
            (3, 'Leonardo Da Vinci', '1452-04-15', '1519-05-02', 'Renacimiento', 'Italiano', 'Leonardo da Vinci (Vinci, Italia, 1452 - Amboise, Francia, 1519) fue un genio renacentista italiano considerado uno de los artistas más influyentes de la historia. Pintor, escultor, arquitecto, científico e inventor, su curiosidad no conocía límites.', 'https://foroalfa.org/imagenes/ilustraciones/1989.jpg'),
            (4, 'Michelangelo Merisi da Caravaggio', '1571-09-29', '1610-07-18', 'Barroco', 'Italiano', 'Fue uno de los pintores más revolucionarios y controvertidos del Barroco italiano.\r\nArtísticamente, transformó la pintura occidental con dos aportaciones fundamentales: el tenebrismo — uso extremo del contraste entre luz y sombra — y el naturalismo, representando figuras religiosas con rostros y cuerpos de personas comunes, alejándose completamente de la idealización renacentista. Sus modelos eran frecuentemente mendigos, prostitutas y gente de la calle.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Bild-Ottavio_Leoni%2C_Caravaggio.jpg/960px-Bild-Ottavio_Leoni%2C_Caravaggio.jpg'),
            (5, 'Andy Warhol', '1928-08-06', '1987-02-22', 'Arte Pop, Arte Moderno', 'Estadounidense', 'Artista plástico y actor estadounidense que desempeñó un papel crucial en el nacimiento y desarrollo del pop art.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Andy_Warhol_at_the_Jewish_Museum_%28by_Bernard_Gotfryd%29_%E2%80%93_LOC.jpg/960px-Andy_Warhol_at_the_Jewish_Museum_%28by_Bernard_Gotfryd%29_%E2%80%93_LOC.jpg'),
            (6, 'Pablo Picasso', '1881-10-25', '1973-04-08', 'Cubismo', 'Español', 'considerado uno de los artistas más influyentes del siglo XX. Cofundador del cubismo junto a Georges Braque, revolucionó el arte moderno al fragmentar las formas y representar múltiples perspectivas simultáneamente.\r\nEntre sus obras más icónicas se encuentran Las señoritas de Aviñón y Guernica, este último un poderoso testimonio contra los horrores de la Guerra Civil Española. A lo largo de su prolífica carrera produjo más de 20.000 obras, explorando distintos estilos y medios con una creatividad incansable.', 'https://www.biografiasyvidas.com/biografia/p/fotos/picasso_pablo.jpg'),
            (7, 'Salvador Dalí', '1904-05-11', '1989-01-23', 'Surrealismo', 'Español', 'Fue un pintor español considerado uno de los máximos exponentes del surrealismo. Nacido en Figueres, Cataluña, desarrolló un estilo visual único e inconfundible, caracterizado por imágenes oníricas, precisión técnica casi fotográfica y una imaginación desbordante.Además de pintor, incursionó en la escultura, el cine, la fotografía, la moda y el diseño, colaborando con figuras como Luis Buñuel y Alfred Hitchcock.\r\nTan excéntrica como su obra fue su personalidad pública: su bigote retorcido, sus declaraciones provocadoras y su teatralidad lo convirtieron en un personaje tan famoso como sus cuadros. Vivió gran parte de su vida junto a su musa y esposa, Gala, quien fue una influencia central en su trabajo.', 'https://www.cultura.gob.ar/media/uploads/dali1.jpg'),
            (8, 'Frida Kahlo', '1907-07-06', '1954-07-13', 'Surrealismo', 'Mexicana', 'Frida Kahlo (1907–1954) fue una pintora mexicana cuya obra y vida se convirtieron en símbolo de resistencia, identidad y dolor transformado en arte. Nacida en Coyoacán, Ciudad de México, su destino quedó marcado por dos grandes traumas: la polio que contrajo a los seis años y el grave accidente de autobús a los dieciocho, que le dejó secuelas físicas de por vida.\r\nDurante su larga recuperación comenzó a pintar, utilizando el lienzo como espejo de su mundo interior. Su estilo, profundamente personal, mezcla elementos del realismo, el simbolismo y el arte popular mexicano, con referencias a la cultura prehispánica y a su propia identidad. Aunque frecuentemente asociada al surrealismo, ella misma rechazó esa etiqueta: \"Nunca pinté sueños. Pinté mi propia realidad.\"', 'https://fundacionerguete.org/files/c13mscerguete/2018-10/17-14-12-46.admin.frida.jpg'),
            (9, 'Henri Matisse', '1869-12-31', '1954-11-03', 'Fauvismo', 'Francés', 'Fue un pintor francés considerado uno de los artistas más influyentes del siglo XX, reconocido por su uso revolucionario del color y su capacidad para transmitir alegría y vitalidad a través de formas aparentemente simples.\r\nNacido en Le Cateau-Cambrésis, en el norte de Francia, descubrió la pintura de manera casi accidental durante una convalecencia, y desde ese momento se entregó al arte con total dedicación. Estudió en París y pronto comenzó a desafiar las convenciones académicas de la época.', 'https://content-historia.nationalgeographic.com.es/medio/2020/10/29/captura-de-pantalla-2020-10-29-a-las-154404_7b96b0c7_550x674.png'),
            (10, 'Alfons Mucha', '1860-07-24', '1939-07-14', 'Art Nouveau', 'Checo', 'Fue un artista checo que alcanzó fama mundial como uno de los máximos representantes del Art Nouveau, el movimiento decorativo que a finales del siglo XIX transformó el diseño gráfico, la ilustración y las artes aplicadas.Su estilo es inconfundible: figuras femeninas idealizadas, de rostros serenos y cabellos ondulantes, enmarcadas en medallones florales, motivos bizantinos y líneas curvas de gran elegancia. Trabajó para marcas, teatros y publicaciones de la época, convirtiendo el cartel publicitario en una forma de arte legítima y accesible para todos.', 'https://upload.wikimedia.org/wikipedia/commons/2/29/Alfons_Mucha_LOC_3c05828u.jpg'),
            (11, 'Edvard Munch', '1863-12-12', '1944-01-23', 'Expresionismo', 'Noruego', 'Fue un pintor y grabador noruego cuya obra exploró con una intensidad sin precedentes las emociones más oscuras del ser humano: la angustia, el miedo, el amor, los celos y la muerte. Es considerado uno de los precursores fundamentales del expresionismo y una de las figuras más influyentes del arte moderno. A diferencia de otros artistas de su época, Munch no buscaba representar el mundo exterior sino el mundo interior, las vibraciones emocionales que los objetos y las personas despiertan en el alma. Sus líneas ondulantes, sus colores perturbadores y sus composiciones cargadas de tensión fueron radicalmente innovadores para su tiempo.', 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg?utm_source=es.wikiquote.org&utm_campaign=index&utm_content=original'),
            (12, 'Tullio Crali', '1910-12-06', '2000-08-05', 'Futurismo', 'Italiano', 'Fue un pintor italiano considerado uno de los representantes más brillantes y tardíos del futurismo, el movimiento artístico de vanguardia que exaltaba la velocidad, la máquina, la energía y la modernidad tecnológica.\r\nNacido en Igalo (actual Montenegro), de nacionalidad italiana, fue en gran medida un artista autodidacta que se unió al movimiento futurista en su segunda etapa, cuando muchos de sus fundadores ya habían fallecido o abandonado sus postulados. Lejos de llegar tarde, Crali le insufló al futurismo una energía renovada y llevó algunas de sus ideas a su máxima expresión visual.', 'https://olympedia-photos.s3.us-east-1.amazonaws.com/920844.jpg'),
            (13, 'Umberto Boccioni', '1882-10-19', '1916-08-17', 'Futurismo', 'Italiano', 'Fue un pintor y escultor italiano considerado la figura más brillante y teoricamente potente del futurismo, el movimiento que él mismo ayudó a definir y que transformó para siempre la manera de representar el movimiento, el tiempo y la energía en el arte moderno.\r\nNacido en Reggio Calabria, se formó en Roma y luego en Milán, ciudad que se convirtió en el escenario principal de su carrera y que aparece repetidamente en su obra como símbolo de la modernidad urbana e industrial que tanto lo fascinaba.\r\nFue uno de los firmantes del Manifiesto de los Pintores Futuristas de 1910, y más que ningún otro artista del movimiento, logró traducir sus ideas en obras de una profundidad y coherencia extraordinarias. Su obsesión central era capturar no el objeto estático, sino el objeto en movimiento, con todo lo que ese movimiento implica: las fuerzas que lo rodean, las emociones que desencadena, su transformación en el tiempo.', 'https://www.biografiasyvidas.com/biografia/b/fotos/boccioni.jpg'),
            (14, 'Gustav Klimt', '1862-07-14', '1919-02-06', 'Art Nouveau', 'Austríaco', 'Fue un pintor austriaco considerado uno de los artistas más sensuales y decorativamente sofisticados de la historia, figura central del Modernismo vienés y fundador de la célebre Secesión de Viena, movimiento que desafió el arte académico oficial en busca de una nueva belleza total y sin jerarquías entre las artes.\r\nNacido en Baumgarten, en las afueras de Viena, se formó como artista decorativo y comenzó su carrera realizando murales y frescos para edificios públicos en un estilo académico convencional. Sin embargo, a finales del siglo XIX dio un giro radical hacia un lenguaje visual completamente propio, provocador y profundamente original.', 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Klimt.jpg'),
            (20, 'Vincent Van Gogh', '1853-03-30', '1890-07-29', 'Postimpresionismo', 'Neerlandés', 'Fue un pintor neerlandés cuya obra marcó un punto de inflexión en la historia del arte moderno. Su vida, tan apasionada como trágica, refleja la lucha constante entre el genio creativo y la fragilidad emocional. Autodidacta y profundamente sensible, Van Gogh exploró la pintura como un lenguaje del alma, utilizando el color y la textura como vehículo de expresión interior. En apenas una década de producción artística, realizó más de 900 cuadros y 1.100 dibujos, creando un legado que transformó la percepción del arte para siempre. Su trazo nervioso, su paleta vibrante y su manera de concebir la luz anticiparon el expresionismo y redefinieron la manera de mirar el mundo.', 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Vincent_van_Gogh_-_s0273V1962_-_Van_Gogh_Museum.jpg'),
            (21, 'Diego Velázquez', '1599-06-06', '1660-08-06', 'Barroco', 'Español', 'Diego Rodríguez de Silva y Velázquez (Sevilla, bautizado el 6 de junio de 1599-Madrid, 6 de agosto de 1660), conocido como Diego Velázquez, fue un pintor barroco español considerado uno de los máximos exponentes de la pintura española y maestro de la pintura universal. Pasó sus primeros años en Sevilla, donde desarrolló un estilo naturalista de iluminación tenebrista, por influencia de Caravaggio y sus seguidores. A los 24 años se trasladó a Madrid, donde fue nombrado pintor del rey Felipe IV y cuatro años después fue ascendido a pintor de cámara, el cargo más importante entre los pintores de la corte. A esta labor dedicó el resto de su vida. ', 'https://www.todocuadros.es/cdn/shop/files/diego-velazquez-autorretrato_1.jpg?v=1684853554&width=600');


            CREATE TABLE IF NOT EXISTS `obras` (
            `id_obra` int(11) NOT NULL AUTO_INCREMENT,
            `nombre` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
            `año_creacion` int(4) NOT NULL,
            `tecnica` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
            `soporte` varchar(50) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
            `corriente_artistica` varchar(200) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
            `descripcion` text CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
            `imagen` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
            `id_artista` int(11) NOT NULL,
            PRIMARY KEY (`id_obra`),
            KEY `id_artista` (`id_artista`),
            CONSTRAINT `obras_ibfk_1` FOREIGN KEY (`id_artista`) REFERENCES `artista` (`id_artista`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

            INSERT INTO `obras` (`id_obra`, `nombre`, `año_creacion`, `tecnica`, `soporte`, `corriente_artistica`, `descripcion`, `imagen`, `id_artista`) VALUES
            (3, 'Impresión, sol naciente', 1872, 'Óleo', 'Lienzo', 'Impresionismo', 'La obra muestra un puerto en Le Havre, la ciudad natal de Monet. Con un énfasis en la luz y el color, la pieza retrata los efectos de un amanecer nebuloso en el agua. Las siluetas de dos botes de remos aparecen en primer plano, mientras que el fondo se compone de las difusas siluetas de barcos y chimeneas industriales.', 'https://es.normandie-tourisme.fr/wp-content/uploads/sites/7/2022/05/claude-monet-Impression-soleil-levant-1872-Musee-Marmottan-Monet-Paris-%C2%A9-SLB-Christian-Baraja-1200x914-1.jpeg', 1),
            (5, 'El puente japonés', 1899, 'Óleo', 'Lienzo', 'Impresionismo', 'Además de capturar la sencilla de elegancia de la estructura, la pieza es una celebración del follaje de su jardín, que incluye sauces llorones, lavanda y nenúfares.', 'https://fta-post-process-output.s3.eu-west-1.amazonaws.com/images/46f9c4c933e26db12cdbd4c7fd1289fd056f5fa0/fullscreen/46f9c4c933e26db12cdbd4c7fd1289fd056f5fa0.jpg', 1),
            (8, 'Encoded Textiles', 2010, 'Tejido artesanal tradicional, Codificación digital', 'Textil, Soporte digital', 'Arte activista y descolonial contemporáneo', 'En la serie Textiles Codificados, Guillermo Bert mantiene vivas las tradiciones culturales usando tecnología moderna para dar voz a personas marginadas, silenciadas e invisibilizadas. En el corazón de esta serie se encuentra el proceso creativo de la codificación: el acto de incorporar mensajes en el tejido de las obras mismas y, en el sentido tecnológico, de convertir símbolos en lenguaje digital. ', 'https://images.squarespace-cdn.com/content/v1/65c010c4a792fd0dd6dc7290/281fb0e8-d9d8-4068-8c8e-de9d7e0545c6/Screen+Shot+2024-02-06+at+10.40.08+PM.png', 2),
            (9, 'La Gioconda (Mona Lisa)', 1503, 'Óleo', 'Tabla', 'Renacimiento', 'La obra representa a una mujer de media figura, identificada tradicionalmente como Lisa Gherardini, esposa de un comerciante florentino.\r\nLa figura aparece sentada, con las manos cruzadas sobre el regazo y una leve sonrisa enigmática que ha fascinado al mundo durante siglos. Viste ropas oscuras y un velo transparente sobre el cabello, propio de la moda de la época.', 'https://concepto.de/wp-content/uploads/2024/08/Mona_Lisa-gioconda-scaled.jpg', 3),
            (10, 'Hombre de Vitruvio', 1490, 'Dibujo a pluma y tinta', 'Papel', 'Renacimiento', 'Este dibujo combina arte y ciencia, explorando la anatomía y las proporciones perfectas del cuerpo humano. Representa una figura masculina desnuda inscrita en un círculo y un cuadrado, basada en las descripciones del arquitecto romano Vitruvio sobre la armonía geométrica.', 'https://content-historia.nationalgeographic.com.es/medio/2025/07/04/hombre-de-vitruvio_1496ec7c_250704111212_1280x1813.webp', 3),
            (11, 'Narciso', 1599, 'Óleo', 'Lienzo', 'Barroco', 'Representa el célebre mito griego del joven que se enamora de su propio reflejo. El reflejo en el agua es la clave narrativa: Narciso y su imagen forman un círculo casi perfecto, simbolizando el encierro del ego sobre sí mismo, la trampa del amor propio que conduce a la muerte.', 'https://upload.wikimedia.org/wikipedia/commons/7/75/Narcissus-Caravaggio_%281594-96%29.jpg', 4),
            (12, 'La Cabeza de Medusa', 1597, 'Óleo', 'Lienzo y rodela de madera de álamo', 'Barroco', 'Representa el instante preciso de la decapitación de la Gorgona, capturando su rostro en un grito de terror y sangre, pintado con un realismo dramático y claroscuro característicos del autor.', 'https://3minutosdearte.com/wp-content/uploads/2018/06/Caravaggio-Cabeza-de-Medusa-1597-e1536759112183.jpg', 4),
            (13, 'Shot Marilyns', 1964, 'Serigrafía (acrílico y tinta serigráfica)', 'Lienzo', 'Arte Pop', 'Son una serie de cinco famosas serigrafías de Andy Warhol que retratan a Marilyn Monroe, marcadas por un incidente donde la artista Dorothy Podber disparó con un revólver a cuatro de ellas en \"The Factory\". La Shot Sage Blue Marilyn se vendió en 2022 por US$195 millones, siendo una de las obras de arte más caras de la historia.', 'https://themarilynreport.com/wp-content/uploads/2022/03/0x0-e1647886259201.jpg', 5),
            (15, 'Mujer con sombrilla', 1875, 'Óleo', 'Tela', 'Impresionismo', 'Un retrato de Madame Monet y el pequeño hijo de la pareja, fue pintado en Argenteuil, donde la familia vivió de 1872 a 1878.\r\nCon animadas pinceladas y una composición enérgica, la pintura probablemente fue creada al exterior. Aunque su esposa —quien porta un vestido que se mueve con el viento y sostiene una bonita sombrilla verde— es el punto focal de la pieza, su entorno también tiene un rol importante en la composición. La fascinación de Monet con el mundo natural también es aparente en su tratamiento del pasto y las flores, que son meticulosamente plasmados con luz del sol y sombras. “La riqueza que alcanzo proviene de la naturaleza, mi fuente de inspiración”, afirmó Monet.', 'https://historia-arte.com/_/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbSI6WyJcL2FydHdvcmtcL2ltYWdlRmlsZVwvNjJlNGVlZmVmMjZkZi5qcGciLCJyZXNpemUsODAwIl19.DOcXL3a6HvCKeKdpWB1MPtNK4RzsboKAe_ZW8hKUfQA.jpg', 1),
            (16, 'Campo de amapolas en Argenteuil', 1873, 'Óleo', 'Lienzo', 'Impresionismo', 'Al igual que Mujer con sombrilla, Campo de amapolas en Argenteuil (1873) muestra a la esposa e hijo de Monet explorando la naturaleza durante un viaje. Esta pieza también muestra el interés de Monet en los exteriores, como es evidente en el prominente campo de las amapolas y el enfoque en el paisaje.\r\nAdemás, Campo de amapolas en Argenteuil exhibe una colorida tendencia hacia incluir toques de color rojo en una composición, algo usado regularmente por los impresionistas.', 'https://historia-arte.com/_/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbSI6WyJcL2FydHdvcmtcL2ltYWdlRmlsZVwvY2xhdWRlLW1vbmV0LTAzNy5qcGciLCJyZXNpemUsODAwIl19.k9e2cmE-VHte0dV49SMDwpHFD8G2SaUt2XJ1ESBVCiU.jp', 1),
            (17, 'La persistencia de la memoria', 1931, 'Óleo', 'Lienzo', 'Surrealismo', 'La imagen surge de la fascinación de Dalí por el subconsciente y las teorías de Freud sobre los sueños. El tiempo, representado por los relojes —símbolo de la razón y la precisión—, aparece aquí derretido, blando, sin autoridad. Es el tiempo tal como se experimenta en el sueño: elástico, irracional, sin medida.\r\nHay también una figura central deforme y amorfa que muchos interpretan como un autorretrato del propio Dalí durmiendo, disolviéndose en el paisaje onírico.\r\nEl propio pintor contó que la inspiración llegó de manera fulminante mientras observaba un queso camembert derritiéndose en la mesa, una tarde en que Gala había salido. En pocas horas, la obra estaba terminada.', 'https://historia-arte.com/_/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbSI6WyJcL2FydHdvcmtcL2ltYWdlRmlsZVwvbnljLTItMjY4LmpwZyIsInJlc2l6ZSwyMDAwLDIwMDAiXX0.kyLjy8saXwwv-oGbJBh7X0tgXbgo4aN-d5IcAxw7A2w.jpg', 7),
            (18, 'La tentación de San Antonio', 1946, 'Óleo', 'Lienzo', 'Surrealismo', 'Es una obra surrealista clave de Salvador Dalí, ubicada en los Museos Reales de Bellas Artes de Bélgica. Muestra a un santo desnudo en el desierto resistiendo tentaciones (lujuria, poder, riqueza) simbolizadas por elefantes con patas de araña y un caballo desbocado, marcando el inicio de su \"período clásico\" o atómico.', 'https://artwork.art-cdn.com/490057/dartemora-pintura-version-la-tentacion-de-san-antonio-salvador-dali.jpg', 7),
            (19, 'Las dos Fridas', 1939, 'Óleo', 'Lienzo', 'Surrealismo', 'Es el autorretrato doble más famoso de Frida Kahlo, pintado tras su divorcio de Diego Rivera. La obra muestra la dualidad de su identidad: una Frida con traje europeo (herencia paterna) y otra con traje de tehuana (raíces mexicanas), conectadas por una vena entre sus corazones expuestos.', 'https://cdn.culturagenial.com/es/imagenes/las-dos-fridas-cke.jpg', 8),
            (20, 'El marco', 1938, 'Óleo', 'Vidrio', 'Surrealismo', 'El cuadro es un autorretrato de formato pequeño en el que Frida se representa a sí misma con su característico atuendo tehuana, flores en el cabello y esa mirada directa, serena y desafiante que se convirtió en su firma visual. Hasta aquí, podría parecer uno más de sus numerosos autorretratos. Lo que hace única a esta obra es su construcción material y conceptual.\r\nLa imagen está literalmente enmarcada dentro de un marco pintado, decorado con pájaros y flores de inspiración popular mexicana, que forma parte de la composición misma. No hay separación entre la obra y su marco: ambos son una unidad, un todo inseparable. Con ese gesto aparentemente sencillo, Frida reflexiona sobre la representación y la identidad: ella misma es la obra, el marco y el sujeto al mismo tiempo.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Frida_Kahlo%2C_The_Frame%2C_1938.jpg/800px-Frida_Kahlo%2C_The_Frame%2C_1938.jpg', 8),
            (21, 'Mujer con sombrero', 1905, 'Óleo', 'Lienzo', 'Fauvismo', 'El cuadro es un retrato de Amélie, esposa de Matisse, presentada de medio cuerpo con un elaborado sombrero y un abanico en la mano. Pero lo que podría haber sido un retrato convencional se convierte en una explosión cromática sin precedentes: el rostro aparece pintado con manchas de verde, rojo, naranja y azul, los colores aplicados de manera libre, casi violenta, sin respetar la anatomía ni la lógica naturalista.', 'https://cdn.culturagenial.com/es/imagenes/mujer-con-sombrero-1905-henri-matisse.jpg', 9),
            (22, 'La alegría de vivir ', 1905, 'Óleo', 'Lienzo', 'Fauvismo', 'Este cuadro toma como tema central el mito griego de Arcadia, una provincia idílica que se caracterizaba por su belleza y tranquilidad. Se suele asociar a Pan, dios de los pastores y los rebaños que habitaba allí y lideraba un estilo de vida en el que predominaba la alegría.\r\nEl tópico fue retomado durante el Renacimiento y más tarde en el Romanticismo como una representación de la utopía, un lugar en el que el ser humano vivía en paz junto a la naturaleza. Así, Matisse quiso presentar un mundo ideal en el que sus habitantes pasan el día descansando, bailando y tocando instrumentos.', 'https://cdn.culturagenial.com/es/imagenes/la-alegria-de-vivir-henri-matisse.jpg', 9),
            (23, 'La danza', 1910, 'Óleo', 'Lienzo', 'Fauvismo', 'Matisse sentía interés por los temas míticos y en este cuadro decidió enfocarse en el regreso a la Edad de Oro en donde el individuo era completamente libre. Esta era una representación que ya había trabajado anteriormente, pues en el fondo de su cuadro \"La alegría de vivir\" se puede ver a un grupo bailando en ronda.\r\nA partir de esta época comienza a saturar los colores. En la tradición, el color había sido un recurso secundario, subordinado a necesidades como la perspectiva y la luz. Aquí, por el contrario, los tonos funcionan como el centro de la pintura y la estructura formal sobre la que se asienta.\r\nAsimismo, se puede notar la influencia de la escultura africana y otras culturas primitivas que fascinaron al pintor. Aquel tipo de iconografía marcó una profunda huella en la representación que hacía de los cuerpos y figuras.', 'https://cdn.culturagenial.com/es/imagenes/la-danza-henri-matisse.jpg', 9),
            (24, 'Gato de los peces rojos', 1914, 'Óleo', 'Lienzo', 'Fauvismo', 'En esta pintura lo que más destaca es la exaltación del color. Ya no busca una representación fiel a la realidad, sino que expresar tonalidades puras y saturadas.\r\n\r\nAquí también puede notarse el desinterés hacia la perspectiva. En el ideario de los fauvistas, los trazos son espontáneos y sueltos. De este modo, no existe profundidad espacial. Se trata de figuras planas y más bien imperfectas que son delineadas como en los dibujos infantiles.', 'https://cdn.culturagenial.com/es/imagenes/gato-con-peces-rojos-henri-matisse.jpg', 9),
            (25, 'El beso', 1909, 'Óleo', 'Lienzo', 'Art Nouveau', 'La obra representa a una pareja encerrada en la intimidad, mientras que el resto de la pintura se disuelve en un fondo brillante con un patrón extravagante. El patrón sugiere el estilo del Art Nouveau y las formas orgánicas del movimiento Arts and Crafts contemporáneos.', 'https://media.admagazine.com/photos/618a648c938f88774ad53f26/master/w_1600%2Cc_limit/75326.jpg', 14),
            (26, 'Retrato de Adele Bloch Bauer', 1907, 'Óleo y oro', 'Tela', 'Art Nouveau', 'Es una de las obras más deslumbrantes y celebradas de Gustav Klimt, conocida popularmente como La dama de oro. Es considerada la Mona Lisa austriaca. El cuadro representa a Adele Bloch-Bauer, esposa de un acaudalado industrial vienés, retratada de frente y ligeramente inclinada, casi disuelta en un fondo de oro puro. Su rostro y sus manos son los únicos elementos claramente figurativos- el resto del cuerpo y el entorno se funden en una explosión de pan de oro, mosaicos, espirales, ojos egipcios y motivos geométricos y orgánicos entrelazados que hacen prácticamente imposible separar la figura del fondo.', 'https://cdn.culturagenial.com/es/imagenes/retrato-de-adele-bloch-bauer.jpg', 14),
            (27, 'Gismonda', 1894, 'Litografía en color', 'Papel', 'Art Nouveau', 'Esta obra es el cartel que cambió la vida de Alphonse Mucha de la noche a la mañana y que inauguró su estilo inconfundible, convirtiéndolo de un ilustrador relativamente desconocido en el artista más solicitado de París.\r\nEl encargo llegó de manera fortuita: era el 26 de diciembre de 1894, día de San Esteban, festividad en que los talleres gráficos estaban prácticamente vacíos. La actriz Sarah Bernhardt, la estrella teatral más famosa de Europa, necesitaba urgentemente un cartel para su obra Gismonda en el Théâtre de la Renaissance. Mucha, que estaba en el taller casi por casualidad, recibió el encargo. El resultado dejó a Bernhardt tan impresionada que lo contrató en exclusiva por cinco años.\r\nEl cartel representa a Bernhardt en su papel protagonista: una figura femenina de tamaño casi natural, vertical y majestuosa, ataviada con un elaborado traje bizantino y sosteniendo una palma decorativa. Su rostro es sereno, idealizado, de una elegancia aristocrática. Sobre su cabeza, un arco de mosaico floral enmarca la figura como si fuera una imagen sagrada medieval.', 'https://cdn.culturagenial.com/es/imagenes/gismonda-sarah-cke.jpg', 10),
            (28, 'Zodíaco', 1896, 'Litografía en color', 'Papel', 'Art Nouveau', 'Fue creada originalmente como calendario decorativo para la editorial Champenois, uno de sus principales clientes en París, y su éxito fue tal que se convirtió en una de las imágenes más reproducidas y coleccionadas de su época.\r\nLa composición muestra una figura femenina de perfil, serena y bellísima, con una elaborada corona floral y vegetal en el cabello. La rodea un gran medallón circular decorado con los doce signos del zodiaco, dispuestos en un anillo que enmarca su rostro como un halo sagrado. El fondo se organiza en franjas decorativas con motivos geométricos y vegetales característicos del Art Nouveau, creando una superficie rica y detallada que equilibra perfectamente lo ornamental con lo figurativo.\r\nLo que distingue a Zodiaco dentro de la producción de Mucha es su capacidad de sintetizar todos los elementos de su estilo en una sola imagen: la figura femenina idealizada, el círculo como elemento estructurador, la fusión entre lo decorativo y lo simbólico, y esa atmósfera entre lo místico y lo terrenal que impregna toda su obra.', 'https://cdn.culturagenial.com/es/imagenes/zodiac-1896-cke.jpg', 10),
            (29, 'La danza', 1898, 'Litografía en color', 'Papel', 'Art Nouveau', 'La obra presenta a una mujer joven envuelta en un drapeado de telas ligeras que se mueven de manera fluida, transmitiendo una sensación de movimiento y ligereza, evocando el acto de la danza. Su postura grácil y la caída de los pétalos refuerzan el dinamismo.\r\nEl artista utiliza una paleta de tonos cálidos (naranjas y rosados) que transmiten sensualidad y armonizan con los verdes y azules fríos del fondo. Esto crea un contraste equilibrado que resalta la figura femenina.\r\nEl cabello largo, ondulado y rojizo de la mujer fluye como un elemento gráfico más de la obra, enfatizando el movimiento y el ritmo.\r\nPor su parte, los motivos florales y el entorno decorativo subrayan la conexión con la naturaleza, una característica esencial del Art Nouveau.', 'https://cdn.culturagenial.com/es/imagenes/la-danza-mucha-2-cke.jpg', 10),
            (30, 'La primavera', 1896, 'Litografía en color', 'Papel', 'Art Nouveau', 'Este cuadro pertenece a su famosa serie de \"Las Estaciones\" que incluye cuatro paneles alegóricos dedicados a la primavera, el verano, otoño e invierno.\r\nLa obra refleja la visión idealizada de la naturaleza y la feminidad que prevalecía en el Art Nouveau. De este modo, la figura femenina funciona como una alegoría de la primavera, representando el renacer de la naturaleza y la vitalidad después del invierno.\r\nAquí predominan los tonos suaves, como los verdes claros, amarillos y rosas pastel, que evocan la frescura y luminosidad de la estación. Asimismo, los elementos circulares y ondulantes (como las flores o el cabello) generan dinamismo y armonía visual.', 'https://cdn.culturagenial.com/es/imagenes/la-primavera-mucha-cke.jpg', 10),
            (31, 'El grito', 1893, 'Óleo, temple y pastel', 'Cartón', 'Expresionismo', 'La escena muestra una figura humana en primer plano, de pie sobre un puente o pasarela, con el cuerpo ondulante y el rostro convertido en una calavera sin género ni edad, con la boca abierta y las manos presionando las mejillas en un gesto de terror absoluto. Detrás, dos figuras oscuras y distantes caminan indiferentes, ajenas al tormento de la figura central. El fiordo de Oslo se extiende al fondo bajo un cielo convulsionado de rojos, naranjas y amarillos que parecen arder y retorcerse.\r\nLo que hace radicalmente original a esta obra es que todo el paisaje participa de la emoción: las líneas del cielo, el agua y el puente no son estáticas sino ondulantes, como si la naturaleza entera vibrara con el mismo horror que siente la figura. No hay separación entre el mundo interior y el exterior: el grito lo atraviesa todo.', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/The_Scream.jpg', 11),
            (32, 'Por la mañana', 1884, 'Óleo', 'Lienzo', 'Expresionismo', 'Se trata de una pintura al óleo sobre lienzo que retrata a una joven sentada en el borde de la cama. La obra destaca por su uso de la luz matutina, marcando una etapa temprana en la carrera del artista noruego, influenciada por el realismo y el impresionismo, antes de su evolución hacia el expresionismo.\r\nEsta obra, a menudo citada en el contexto de sus primeros años de formación, muestra una aproximación más sutil a la luz y la atmósfera en comparación con sus trabajos psicológicos posteriores.', 'https://www.ttamayo.com/wp-content/uploads/2016/11/Edvard-Munch-Morning-1884-1024x956.jpg', 11),
            (33, 'Misión aérea', 1935, 'Óleo', 'Lienzo', 'Futurismo', 'La obra representa la visión desde la cabina de un avión en misión, con la perspectiva vertiginosa y dinámica característica de Crali: el horizonte inclinado, la tierra fragmentada en planos geométricos abajo, y la sensación física de velocidad y altura que coloca al espectador dentro de la aeronave.', 'https://www.cosasdearquitectos.com/wp-content/uploads/Tullio-Crali-1935-Missione-Aerea-1024x608.jpg', 12),
            (34, 'Picado sobre la ciudad', 1939, 'Óleo', 'Tela', 'Futurismo', 'La composición muestra la vista desde la cabina de un avión en picada vertical sobre una ciudad, con una perspectiva absolutamente vertiginosa que coloca al espectador en el lugar del piloto. Los edificios abajo aparecen distorsionados, escorzados al extremo, aplastados por la velocidad y el ángulo de descenso. Crali abandona la geometrización futurista y crea una obra curvilínea en la que sintetiza no solo lo que se ve, sino lo que se siente: la libertad, la velocidad, la máquina.', 'https://www.cosasdearquitectos.com/wp-content/uploads/Tullio-Crali-1939-Nose-Dive-on-the-City-768x651.jpg', 12),
            (35, 'Disturbios en la galería', 1910, 'Óleo', 'Lienzo', 'Futurismo', 'La obra muestra a espectadores frenéticos en torno a una impactante pelea entre dos mujeres —que se cree que eran prostitutas— en el famoso centro comercial cubierto de Milán, la Galleria Vittorio Emanuele II. La multitud representa a la burguesía de la época, y aparece caótica y desbordada. \r\nEjecutada en los meses inmediatamente posteriores a su firma del Manifiesto Técnico de la Pintura Futurista, Boccioni utilizó y llevó al extremo la técnica divisionista para estudiar los movimientos de la multitud y crear efectos sin precedentes de luz y dinamismo, acentuados por el uso de colores complementarios.', 'https://m.media-amazon.com/images/I/81d2QnPWo2L._AC_SX679_.jpg', 13),
            (36, 'Paisaje mediterráneo', 1952, 'Óleo', 'Lienzo', 'Cubismo', '\"Paisaje mediterráneo\" (1952/1953) de Pablo Picasso es una obra cubista que representa la costa del Mediterráneo, a menudo inspirada en Grecia o el sur de Francia. Utiliza formas fragmentadas, colores vibrantes y estructuras geométricas para capturar la arquitectura, jardines, palmeras y el mar, reflejando su pasión por la luz y el paisaje del sur.', 'https://www.todocuadros.es/cdn/shop/files/paisaje-mediterraneo-picasso-ver4.jpg', 6),
            (37, 'El sueño', 1932, 'Óleo', 'Lienzo', 'Cubismo', 'Se trata de un famoso óleo sobre lienzo (\\(130 \\times 97\\) cm) de estilo cubista y surrealista que retrata a su amante Marie-Thérèse Walter durmiendo en un sillón rojo. La obra destaca por sus formas curvilíneas, colores vibrantes y la distorsión del rostro dividido, reflejando una intensa mezcla de erotismo, ternura y sueño.', 'https://lacamaradelarte.com/wp-content/uploads/2023/08/picasso-el-sueno-1932-752x1024.jpg', 6),
            (39, 'La noche estrellada', 1889, 'Óleo', 'Lienzo', 'Postimpresionismo', 'Se trata de una obra maestra postimpresionista que representa una vista imaginaria desde su ventana en el sanatorio de Saint-Rémy, Francia. Combina intensos azules y amarillos con pinceladas enérgicas (empaste) para mostrar un cielo turbulento con espirales, 11 estrellas vibrantes y una luna menguante, contrastando con la calma de un pueblo inferior. Fue pintada en junio de 1889, durante uno de los periodos más oscuros y convulsos de la salud mental de Van Gogh. Más que un paisaje real, es una expresión subjetiva de su mundo interior, mezclando realidad con fantasía y emoción.', 'https://i.redd.it/r44d0f4o4xj91.jpg', 20),
            (41, 'Terraza de café por la noche', 1888, 'Óleo', 'Lienzo', 'Postimpresionismo', 'También conocido como \"Café Terrace at Night\", este cuadro se erige como una de las obras más emblemáticas de Vincent van Gogh. Es, sin duda, uno de los iconos más reconocibles de su breve pero intensísima carrera artística, donde el color, la luz y la emoción alcanzan una armonía casi mística.\r\nVan Gogh pintó esta escena en septiembre de 1888, durante su estancia en la ciudad francesa de Arlés. Allí encontró inspiración en la vida nocturna y en el ambiente sereno de las terrazas del sur de Francia. Lo fascinante es que la pintura representa un lugar real: la Place du Forum, que aún hoy se conserva casi idéntica, permitiendo a los visitantes sentarse exactamente en el café donde el artista colocó su caballete hace más de un siglo.\r\nLa obra es un canto a la luz artificial y a la noche estrellada. Van Gogh logró capturar la atmósfera sin usar el color negro, algo revolucionario en la pintura nocturna de su tiempo. En su lugar, utilizó una paleta de amarillos dorados, azules cobalto y verdes intensos para transmitir la calidez de la lámpara de gas y el frescor del cielo. Curiosamente, se cree que el artista insinuó en la composición una sutil Última Cena: doce figuras bajo la luz del café y un camarero en el centro, iluminado como un Cristo moderno.', 'https://www.todocuadros.es/cdn/shop/files/cafe-terrace-van-gogh-v3-ver4.jpg?v=1753784254&width=600', 20),
            (42, 'La siesta', 1889, 'Óleo', 'Lienzo', 'Postimpresionismo', 'El cuadro La siesta fue pintado por Vincent van Gogh mientras se encontraba internado en un asilo para enfermos mentales, en Saint Remy de Provence, Francia. La composición está inspirada en un dibujo de Millet, según Vincent comenta a su primo en una carta. Aunque copiada la idea, los expertos aseguran que en esta obra se aprecia el estilo personal de Van Gogh con toda su fuerza, caracterizado en este cuadro por la construcción cromática basada en contrastes de colores complementarios: azul/violeta y amarillo/naranja. Este cuadro se encuentra expuesto actualmente en el Museo de Orsay, París.', 'https://www.todocuadros.es/cdn/shop/files/la-siesta-van-gogh-ver4.jpg', 20),
            (43, 'Bodegón con membrillos', 1888, 'Óleo', 'Lienzo', 'Postimpresionismo', 'Bodegón pintado por Vincent van Gogh entre los años 1888 y 1889. Se trata de una temática escasa en la obra del pintor, la obra presenta 14 membrillos dispuestos sobre una tela azul y fondo de pared marrón. Los detalles de brillo, cromática y sobre todo las pinceladas hacen que la autoría de Vincent sea inmediatamente reconocible. Actualmente la obra se encuentra en la Galería Nuevos Maestros, perteneciente a la institución Colecciones estatales de arte de Dresde, Alemania.', 'https://www.todocuadros.es/cdn/shop/files/bodegon-membrillos-van-gogh-ver4.jpg?v=1753347060&width=600', 20),
            (44, 'Las meninas', 1657, 'Óleo', 'Lienzo', 'Barroco', 'Las Meninas (1656) es la obra maestra indiscutible de Velázquez y una de las composiciones más analizadas y admiradas de toda la historia del arte occidental. Realizada durante su etapa como pintor de cámara de Felipe IV, esta pintura monumental ofrece una compleja reflexión sobre la representación, el poder y la mirada. El personaje central es la infanta Margarita Teresa de Austria, rodeada por sus damas de honor, conocidos como “meninas”, junto a bufones, un mastín y el propio artista, que se autorretrata mientras trabaja frente al espectador.', 'https://www.todocuadros.es/cdn/shop/files/velazquez-las-meninas-ver4.jpg?v=1753185969&width=600', 21);
            
            SQL;

            foreach (explode (';', $sql) as $statement){
                $statement = trim($statement);
                if (!empty($statement)){
                    $this->db->exec($statement);
                }
            }
        }
    }
}